/* Generated by re2c 2.2 on Tue Feb 22 03:38:04 2022 */
#line 1 "lex.re.cc"
#include <cstdlib>
#include "calc_ast.h"
#include "calc.hpp"


bool yylex(const char *cursor, std::vector<std::pair<calc::Token, std::shared_ptr<Node>>> &tokens)
{
    int num;
    char *marker;
    const char *token;

    tokens.clear();

    loop:
    token = cursor;
    
#line 23 "lex.cc"
{
	char yych;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case ' ':	goto yy6;
	case '\n':	goto yy8;
	case '(':	goto yy10;
	case ')':	goto yy12;
	case '*':	goto yy14;
	case '+':	goto yy16;
	case '-':	goto yy18;
	case '/':	goto yy20;
	case '0':	goto yy22;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	default:	goto yy4;
	}
yy2:
	++cursor;
#line 30 "lex.re.cc"
	{ tokens.push_back(std::make_pair(calc::token_eof, nullptr)); return true; }
#line 54 "lex.cc"
yy4:
	++cursor;
#line 29 "lex.re.cc"
	{ return false; }
#line 59 "lex.cc"
yy6:
	++cursor;
#line 31 "lex.re.cc"
	{ goto loop; }
#line 64 "lex.cc"
yy8:
	++cursor;
#line 39 "lex.re.cc"
	{ tokens.push_back(std::make_pair(calc::token_NL, nullptr)); goto loop; }
#line 69 "lex.cc"
yy10:
	++cursor;
#line 37 "lex.re.cc"
	{ tokens.push_back(std::make_pair(calc::token_LP, nullptr)); goto loop; }
#line 74 "lex.cc"
yy12:
	++cursor;
#line 38 "lex.re.cc"
	{ tokens.push_back(std::make_pair(calc::token_RP, nullptr)); goto loop; }
#line 79 "lex.cc"
yy14:
	++cursor;
#line 35 "lex.re.cc"
	{ tokens.push_back(std::make_pair(calc::token_MUL, nullptr)); goto loop; }
#line 84 "lex.cc"
yy16:
	++cursor;
#line 33 "lex.re.cc"
	{ tokens.push_back(std::make_pair(calc::token_ADD, nullptr)); goto loop; }
#line 89 "lex.cc"
yy18:
	++cursor;
#line 34 "lex.re.cc"
	{ tokens.push_back(std::make_pair(calc::token_SUB, nullptr)); goto loop; }
#line 94 "lex.cc"
yy20:
	++cursor;
#line 36 "lex.re.cc"
	{ tokens.push_back(std::make_pair(calc::token_DIV, nullptr)); goto loop; }
#line 99 "lex.cc"
yy22:
	++cursor;
#line 41 "lex.re.cc"
	{
            num = 0;
            tokens.push_back(std::make_pair(calc::token_Number, std::make_shared<Number>(0)));
            goto loop;
        }
#line 108 "lex.cc"
yy24:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	default:	goto yy26;
	}
yy26:
#line 47 "lex.re.cc"
	{
            size_t size = cursor - token;
            char *yytext = (char *)calloc(size, sizeof(char));
            memcpy(yytext, token, size);
            num = atoi(yytext);
            tokens.push_back(std::make_pair(calc::token_Number, std::make_shared<Number>(num)));
            free(yytext);
            goto loop;
        }
#line 135 "lex.cc"
}
#line 56 "lex.re.cc"

}
